import Navbar from '@/components/Navbar';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Footer from '@/components/Footer';
import StoreProvider from './StoreProvider';
import QueryProvider from './QueryClientProvider';
import { Suspense } from 'react';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <QueryProvider>
          <body
            className={`${inter.className} antialiased min-h-screen  grid grid-rows-[90px_1fr] `}
          >
            <Suspense fallback={<div>Loading...</div>}>
              <Navbar />
              {/* <div className="container-box w-full !py-8 !pb-10 relative"> */}
              {children}
              {/* </div> */}

              <Footer />
            </Suspense>
          </body>
        </QueryProvider>
      </StoreProvider>
    </html>
  );
}
